# Generated by Django 5.1.5 on 2025-01-15 19:30

import django.db.models.deletion
import egyptian_phone_validator.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=245, unique=True)),
                ('phone', models.CharField(help_text='Enter a valid Egyptian phone number (e.g., 01012345678).', max_length=11, validators=[egyptian_phone_validator.validators.validate_egyptian_phone_number])),
                ('national_number', models.CharField(max_length=15, unique=True)),
                ('adress', models.TextField(max_length=150)),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('Admin', 'Admin'), ('Department Head', 'Department Head'), ('Manager', 'Manager'), ('Employee', 'Employee')], max_length=100)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='department.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
