# Generated by Django 5.1.5 on 2025-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
    ]
